export const invertors = [
    {
        id: 1,
        modelName: "Radian E-Series GS7048E ",
        producer: "Outback",
        pmax: 7900,
        width: 71.1,
        height:40.6,
        depth:22.1,
        weight:56.7,
        price:16339,
        powerType:"mono",
        type:"hybrid",
        efficiency:96
    },
    {
        id: 2,
        modelName: "Primo Gen24 6.0 Plus",
        producer: "Fronius",
        pmax: 9000,
        width: 52.8,
        height:47.4,
        depth:16.4,
        weight:16.6,
        price:11398,
        powerType:"mono",
        type:"hybrid",
        efficiency:97.4
    },
    {
        id: 3,
        modelName: "SUN2000-5KTL-L1",
        producer: "Huawei",
        pmax: 7500,
        width: 36.5,
        height:36.5,
        depth:14,
        weight:12.3,
        price:5886,
        powerType:"mono",
        type:"hybrid",
        efficiency:98.4
    },
    {
        id: 4,
        modelName: "SUN2000-3.68KTL-L1",
        producer: "Huawei",
        pmax: 5520,
        width: 36.5,
        height:36.5,
        depth:14,
        weight:12.3,
        price:5212,
        powerType:"mono",
        type:"hybrid",
        efficiency:98.4
    },
];